#index:
#    path: /
#    controller: App\Controller\DefaultController::index
movies:
    type:     rest
    resource: App\Controller\MoviesController
#ratings:
#    type:     rest
#    resource: App\Controller\RatingsController